# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1prototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tide',
            name='parameterName',
            field=models.CharField(max_length=200),
        ),
    ]
