# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1prototype', '0004_auto_20170522_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='chlorosity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=1)),
                ('locationName', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
    ]
